### ISSUE TITLE
Mimimum PHP requirements for next version.

### ISSUE THREAD

**Issue by MarkMaldaba** [adobo/agendav#132]
Is the next version of AgenDAV really going to require PHP 5.4?

I don't know about other users, but we won't be in a position to upgrade to 5.4 for quite a while, and so would have to maintain my own 5.3-compatible fork.

What is it that has raised this version requirement, and is there any way of working around it so that 5.3 is still supported?

[FYI when I last did a proper check, about 10 months ago[1], less that 19% of popular web servers were running PHP 5.4 or higher, and whilst this figure has no doubt gone up (I don't have up-to-date figures), 5.4 uptake is still pretty low in comparison to 5.3]

[1] https://github.com/Block8/PHPCI/pull/398#issuecomment-42900980

**Comment by mmoll** [comment]
PHP 5.3 is EOL upstream since over half a year and all the major distros have updated or provided newer versions via backports/dotdeb/scl, please go for 5.4+ :)

**Comment by MarkMaldaba** [comment]
Centos 6 uses PHP 5.3.3 and has an end-of-life of November 2020, therefore 5.3 will be around for some time.

PHP 5.3 is currently used by 44% [1] of the top 10 million websites [2], compared to 28% that use 5.4.

Regardless of the official status, 5.3 is still overwhelmingly the most commonly installed PHP version in real-world use.

What PHP 5.4 features are you using that mean 5.3 support is not possible?

[1] http://w3techs.com/technologies/details/pl-php/5/all
[2] http://w3techs.com/technologies

**Comment by mmoll** [comment]
The corresponding SCLs are available also for CentOS 6:
https://www.softwarecollections.org/en/scls/rhscl/php54/
https://www.softwarecollections.org/en/scls/rhscl/php55/

**Comment by evert** [comment]
It would be one thing to ask for AgenDAV to support PHP 5.3 in the 1.x versions, because it has in the past (I don't know what @adobo 's stance on that is though).

But if you want to upgrade to a new major version (2.x) it's also completely fair to also require newer dependencies.

**Comment by MarkMaldaba** [comment]
@evert - I agree that major system requirements changes should require a major version increment.  As far as I can see the 'develop' branch is numbered 1.3, so that is not currently the case here.  If BC is going to be broken then you're right, it probably should be released as 2.0 instead.

I also agree that it's completely fair for a new version to require higher dependencies.

However, neither of those is really my point.  I'm not saying that it is wrong to increase the version requirements, I just want to understand what 5.4 features are being used that caused this breakage.  Backwards-compatibility is often broken without giving any thought to the impact it will have, and in a lot of cases it can be avoided fairly trivially.

For example, if the project has been rewritten to make extensive use of traits, then this is a design decision to make full use of the new features provided by 5.4 to provide an improved system architecture, and this is therefore a very good reason to raise your minimum requirements.

However, if the only issue is that you want to use short array syntax, then this is basically raising your minimum requirements in order to save yourself from typing 5 characters when declaring an array.  This is a very bad reason to raise your minimum requirements.

So, I ask again, what are the PHP 5.4 features that are being used here?

**Comment by evert** [comment]
Well, I should prefix this by saying, this is not my project. So I can't speak for to the project.

However, I do know that agendav is going use [sabre/vobject](https://github.com/fruux/sabre-vobject) as a new dependency. This project _is_ mine and already requires PHP 5.4. I don't know if that's 100% of the reason, but by switching to vobject, the minimum version would automatically have to be PHP 5.4.

**Comment by evert** [comment]
I can't speak for the project, because it's not my project. But my guess is, that in the new `develop` branch, there's a lot of new dependencies:

https://github.com/adobo/agendav/blob/develop/web/composer.json

One of those dependencies is my project [sabre/dav](https://github.com/fruux/sabre-dav) and requires PHP 5.4 itself, and I'm sure there are other dependencies in that list that require PHP 5.4.

So it may not just be language features, it could also because most other project these days require PHP 5.4 as a minimum version.

**Comment by MarkMaldaba** [comment]
Well, fair enough, if that's the case (would like to have that confirmed).

Out of interest - what are you using in sabre/dav that requires 5.4?

**Comment by evert** [comment]
Here's a few:

1. New array syntax is used literally everywhere.
2. Support for `$this` in closures.
3. traits
4. array dereferencing.

The current stable sabre/dav is 2.1, 2.2 will also support PHP 5.4 and for 2.3 we're actually making 5.5 the minimum. Partly because we want Generator support which can potentially really speed things up, but there's a few other reasons we drop support for older PHP versions:

* Even if we don't absolutely _require_ the new features, it makes it more fun to continue working on these projects. If it's more fun, we can be more productive. Don't forget that open source projects tend to run on volunteers ;)
* We have less testing to do. It's actually a lot of work to always keep support for older versions. There's many obscure bugs that require weird workarounds. Over time we've been able to remove them one by one.
* By forcing people to upgrade their PHP, the overall user experience is better. Newer PHP versions are always way faster, which makes sabre/dav seem faster.
* We want to encourage people to use up to date software, and run operating systems that stay up to date. An 'up to date world' is better for developers, and in turn also better for end-users.

But we maintain older versions for quite some time. This allows us to have a product that feels like it's very modern, but it's also a stable product for the people that need it to be stable for a long time.

**Comment by adobo** [comment]
Next AgenDAV release will be 2.0.0. Seems that I forgot to update the changelog and it still talked about 1.3.0. My fault.

There are multiple reasons to require PHP 5.4, and @evert pointed all of them right. The main reason for the switch is that some dependencies (including `sabre/dav`) require PHP 5.4, but I absolutely agree with the rest of the reasons Evert gave on the previous comment.

PHP 5.4 has been available since 2012, so an updated PHP should be easy to find for most operating systems.

**Comment by MarkMaldaba** [comment]
Fair enough - seems like dependencies require it and that the use of PHP 5.4 features is quite extensive.

@evert Your points are good (especially point 1, which is an unfortunate reality of the open-source world), though the final point is a bit flawed (it's good to encourage people to upgrade, but if they can't you effectively make the problem worse as they end up continuing to use older software, possibly lacking important security patches, and also increase the likelihood that they will switch to a competitor) and I'm always worried when developers talk about 'forcing' their users to do things.  However, on balance, this is probably the right move for this project.

At the moment we can't upgrade (there are client projects on the server that are known to not support 5.4) therefore I will have to maintain my own 5.3 fork for a while, and back-port updates where possible.  Hopefully that won't be the case for too long, but I can well see that it might be!
