### ISSUE TITLE
inconsistent language identifiers

### ISSUE THREAD

**Issue by mmoll** [adobo/agendav#143]
For some languages there's an added territory code, some are missing it, for Czech there's cs and cs_CZ. It would be good to have this standardized to one possibility.

Having just the language means bigger coverage (e.g. German is an official language not only in Germany), but I'm unsure about differences between e.g. pt_PT and pt_BR or es_ES and the variants in South/Middle American countries.

**Comment by adobo** [comment]
While I agree with you that it would be great to concentrate efforts on translating into non territory specific languages (i.e. *en* instead of *en_US* + *en_GB*), there are subtle differences between them and I believe this is actually a matter of national identity. It is also hard to keep translations completely neutral.

Perhaps language listing inside Preferences should include the territory next to each language name. Do you think that would help?

**Comment by mmoll** [comment]
Yes, I guess it's best also for non-techsavy users to display the territory when there is one.
