### ISSUE TITLE
Synology Caldav Access over Nginx port 443 HTTPS

### ISSUE THREAD

**Issue by TerranoLuna** [adobo/agendav#157]
I use NGINX Proxy to block port access.
So, the following config is good: $app['caldav.baseurl'] = 'https://caldav.mondomaine.fr:5006/calendars/';
This use directly WebDav HTTPS port without to pass in NGINX.

But with the following config: $app['caldav.baseurl'] = 'https://caldav.mondomaine.fr:443/calendars/';
This use Nginx to redirect in localhost to 5006 Port under HTTPS.
The application say to me "Username or password incorrect"...

[2015-12-17.txt](https://github.com/adobo/agendav/files/65364/2015-12-17.txt)
[http-2015-12-17.txt](https://github.com/adobo/agendav/files/65365/http-2015-12-17.txt)

PS : https://caldav.mondomaine.fr:443/calendars/ is the same link configured on my Apple Device and no problem found.

**Comment by adobo** [comment]
Oops, I totally missed this issue! The OPTIONS response doesn't even have a `DAV:` header. That's why AgenDAV doesn't go further. Synology CalDAV server is somehow not completely compliant.

BTW be careful with your password, you posted it along your log. Since beta2 `Authorization` headers are cloaked, but beta1 just saved them with the rest of headers.
