### ISSUE TITLE
"league/fractal" version mismatch

### ISSUE THREAD

**Issue by anedisi** [adobo/agendav#158]
"league/fractal": "~0.12.0", is the last version that is compatible with current dev branch.

version .13
has this

    protected function getIdFromData(array $data)
    {
        if (!array_key_exists('id', $data)) {
            throw new InvalidArgumentException(
                'JSON API resource objects MUST have a valid id'
            );
        }
        return $data['id'];
    }

also after update it reports validator missing so i added 

"symfony/validator": "~2.7|3.0.*",

**Comment by adobo** [comment]
You are absolutely right about `league/fractal`, it should be specified as `~0.12.0`. Should be fixed now!

By the way, the `composer.lock` file is also distributed to avoid this kind of issues. You should always use `composer install` instead of `composer update`.

This information will be really useful for future updates.

Thank you!
