### ISSUE TITLE
Complete documentation about installation

### ISSUE THREAD

**Issue by Phyks** [adobo/agendav#195]
Hi,

I tried to install an agendav instance but ran into some issues. I can make a PR to complete the doc, if I manage to sort out the installation procedure :)

1. First, I had an issue with `Doctrine` and `binlog_format`, pretty similar to https://github.com/owncloud/core/issues/16008. Fixed it by switching to `binlog_format = MIXED`, but putting some comment about it in the doc would be really helpful I guess.

2. I am trying to run it from a subfolder. Apparently, `app.request.basepath` is an empty string (not sure why), and it fails to load assets from the correct path. For now, I monkey patched it by hardcoding `assets_root`, but this is not really clean, and https://github.com/adobo/agendav/pull/180 makes me think there is a cleaner way to handle this.

3. More important is that I chose to install from Git, to be able to update as simply as a `git checkout`. Following the [installation procedure](http://docs.agendav.org/en/stable/admin/installation/), I don't have any `-built` assets. And I cannot find the right command to build them :/

Thanks!

**Comment by adobo** [comment]
Hi, thank you for your comments!

I didn't know about the `binlog_format` issue, but I'll sure add it to the documentation. Did you find it while creating the database schema or just after trying to access AgenDAV with a browser?

Subfolder issues should be fixed after switching to the Symfony Asset Component instead of rolling our own. It's ready to use on the `develop` branch.

Documentation about generating assets has been also added, should be covered by http://agendav.readthedocs.io/en/develop/admin/installation/#download-dependencies-and-generate-assets-only-for-git and http://agendav.readthedocs.io/en/develop/development/#building-assets .

Thank you!

**Comment by Phyks** [comment]
Hi,

> I didn't know about the binlog_format issue, but I'll sure add it to the documentation. Did you find it while creating the database schema or just after trying to access AgenDAV with a browser?

This was a while ago, but as far as I could remember, I found it when migrating the db.

> Documentation about generating assets has been also added
Thanks! However, note that these `npm` scripts are not present under the current stable release (2.0.0) : https://github.com/adobo/agendav/blob/2.0.0/package.json#L9.

In the meantime, and as the subfolder issues should be fixed in `develop` branch, I'll switch to this one and let you know.

**Comment by Phyks** [comment]
Everything seems to be working fine with `develop` branch. Except for the `doctrine` issue, I think this issue can be safely closed.

**Comment by adobo** [comment]
Glad to hear that! I just added a note about the binary logging format on the docs.

Thank you!
